### ISSUE TITLE
Display all post belonging to the first level tag

### ISSUE THREAD

**Issue by 6nanyi** [usememos/memos#4019] opened 2024-10-14 04:54 UTC
### Describe the solution you'd like

When I use multi-level tags, clicking on a first level tag cannot display all the content belonging to that first level tag. In other words, I want to search for all content belonging to the first level tag, rather than searching for content belonging to the second level tag separately.
![Snipaste_2024-10-14_12-51-14](https://github.com/user-attachments/assets/926e3a65-63c6-4c46-b867-b974b7cb3cca)
![Snipaste_2024-10-14_12-51-36](https://github.com/user-attachments/assets/1b11d40b-54e1-4487-8253-b42e0de7e463)

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment] 2024-10-14 08:24
Duplicate of https://github.com/usememos/memos/issues/3948

This has been resolved in versions > 0.22.5

**Closed** 2024-10-14 12:52 UTC
Labels: enhancement
