### ISSUE TITLE
error when app start

### ISSUE THREAD

**Issue by eshion** [usememos/memos#2719] opened 2024-01-08 06:12 UTC
### Describe the bug

ERROR memos/main.go:57 failed to migrate db {"error": "failed to exec latest schema: Error 1105 (HY000): unknown error: Code: UNAVAILABLE\nserver does not allow insecure connections, client must use SSL/TLS\n"

### Steps to reproduce

[env]
  MEMOS_DRIVER = "mysql"
  MEMOS_DSN = "some_mysql_dsn"

### The version of Memos you're using

ghcr.io/usememos/memos:latest

**Comment by jhademcconnell** [comment] 2024-01-08 12:53
This is working as intended. You need to set up SSL or disallow SSL from the error message: `UNAVAILABLE\nserver does not allow insecure connections, client must use SSL/TLS\n`

https://stackoverflow.com/questions/34189756/warning-about-ssl-connection-when-connecting-to-mysql-database

**Comment by boojack** [comment] 2024-01-09 16:04
Fixed with https://github.com/usememos/memos/commit/9c663b1ba299fb945c99acaa0542ee0b9fecd586

**Closed by boojack** 2024-01-09 16:04 UTC
Labels: bug
