### ISSUE TITLE
贴的代码有#的话，会被当做标签？

### ISSUE THREAD

**Issue by RustyNailPlease** [usememos/memos#803] opened 2022-12-21 00:41 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/117324885/208793787-744a9167-9c99-407c-8b3e-29bd8ee1d2d7.png)

### Steps to reproduce

rt

**Comment by Zeng1998** [comment] 2022-12-21 01:02
Duplicate of #629

**Closed** 2022-12-22 03:33 UTC
Labels: bug
