### ISSUE TITLE
Translation service locked work on project translation

### ISSUE THREAD

**Issue by click0** [usememos/memos#4069] opened 2024-10-30 02:17 UTC
### Describe the bug

Translation service [locked work ](https://hosted.weblate.org/projects/memos-i18n/english/#alerts)on project translation

```
Could not merge the repository.

Weblate could not merge upstream changes while updating the repository.

Rebasing (1/3)
Auto-merging web/src/locales/ca.json
CONFLICT (add/add): Merge conflict in web/src/locales/ca.json
error: could not apply 37b3bc2f... Added translation using Weblate (Catalan)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 37b3bc2f... Added translation using Weblate (Catalan)
 (1)
 ...
```

### Steps to reproduce

Go to the translation service and read the notifications

### The version of Memos you're using.

v0.22.5

**Comment by RoccoSmit** [comment] 2024-10-30 02:24
Duplicate of https://github.com/usememos/memos/issues/3924

Please see linked issue for how to update translations

**Closed** 2024-10-30 04:20 UTC
Labels: bug
