### ISSUE TITLE
The date cannot be changed in the iPhone Safari or Edge browser

### ISSUE THREAD

**Issue by fattyhk** [usememos/memos#3827] opened 2024-08-24 03:04 UTC
### Describe the bug

The date cannot be changed in the iPhone Safari or Edge browser,show "invaild date".

### Steps to reproduce

1.in Edge open memos
2.edit memo
3.click the date
4.show "invaild date".

### The version of Memos you're using.

0.22.4  

### Screenshots or additional context

![日期修改](https://github.com/user-attachments/assets/a19700df-f494-49c4-9dca-0e89edc69245)

**Comment by RoccoSmit** [comment] 2024-08-24 03:16
Potential duplicate of Allow memo date change Firefox / Safari (https://github.com/usememos/memos/issues/3812)

**Comment by fattyhk** [comment] 2024-08-24 03:36
the same bug in iphone Edge。

**Closed** 2024-08-24 12:32 UTC
Labels: bug

**Comment by fattyhk** [comment] 2024-08-25 14:15
@boojack why closed it? if can't edit date in iphone,It will be inconvenient。
