### ISSUE TITLE
Two bugs about the Daily Review page

### ISSUE THREAD

**Issue by dwong33** [usememos/memos#2540] opened 2023-11-22 10:03 UTC
### Describe the bug

![Screenshot 2023-11-22 04 41 45](https://github.com/usememos/memos/assets/12155059/6a3eb3fa-5ebb-4dd1-b12e-9aa37558752f)

There seems to be two bugs about the Daily Review page:

1. When I select a date from the calendar, the daily review panel will show the memos a day before. As shown in the screenshot above, I click on the calendar to show memos on Nov 22, it shows the memos from Nov 22, which is correct. But at the top, the date shown was a day earlier, Nov 21.
2. I believe the blue dots next to the date indicate that there are memos available on that day. But as shown in the above screenshot, there are no blue dots from Nov 6 to Nov 21, but there are actually memos throughout this period.

### Steps to reproduce

1. Go to daily review
2. Navigate through the dates
3. Click on the calendar

**Comment by athurg** [comment] 2023-11-23 02:10
I can't reproduce those bugs in my *Memos* . Could you please provide the version you currently running on?

**Comment by dwong33** [comment] 2023-11-23 16:44
I observe this issue starting from v0.17.0.
I am now using v0.17.1

I skipped the whole v0.16.x, upgraded directly from v0.15.x to v0.17.0, not sure whether it would affect the migration.

The environment is on a docker located in a NAS.

**Comment by dwong33** [comment] 2023-12-06 21:32
So it was strange, when December comes, the review function for December functions normally.
While for November, the problems described above persisted.

It seemed that it would reset when the new month comes.  

Please see the two captures for illustration, thank you.
![Screenshot 2023-12-06 16 30 12](https://github.com/usememos/memos/assets/12155059/d2f90740-0025-4d73-8f8a-5a5531ee186b)
![Screenshot 2023-12-06 16 30 02](https://github.com/usememos/memos/assets/12155059/cb3ff495-a722-42a4-a32e-df93bb9e8084)

**Comment by boojack** [comment] 2023-12-23 12:05
Maybe fixed in the latest version.

**Closed by boojack** 2023-12-23 12:05 UTC
Labels: bug
