### ISSUE TITLE
隐私问题：内容里面的图片复制链接的时候，直接给别人不登录也可以看到，是否意味着可以让搜索引擎爬取到

### ISSUE THREAD

**Issue by wk-coder** [usememos/memos#825] opened 2022-12-22 07:27 UTC
### Describe the bug

内容里面的图片复制链接的时候，直接给别人不登录也可以看到，是否意味着可以让搜索引擎爬取到

### Steps to reproduce

1.先正常创建内容带图片
2.复制链接到别处
3.可以打开链接看到图片

**Comment by m-gschwandtner** [comment] 2022-12-23 23:03
If the image is not in any Public memo, a crawler will nor find / index it.

Since you can't get a list of all available files, you would need to try random combinations until you find an image, which a crawler is not going to do.

Switching a memo from public to private will normally not remove an image from the search index tough.

**Comment by Zeng1998** [comment] 2023-02-14 03:40
Duplicate of #822

**Closed by Zeng1998** 2023-02-14 03:40 UTC
Labels: bug
