### ISSUE TITLE
SSO - signup is shown as enabled in UI on initial setup but it is set as false internally

### ISSUE THREAD

**Issue by debugger24** [usememos/memos#2519] opened 2023-11-15 19:34 UTC
### Describe the bug

When admin had setup SSO in memos, normal users should be able to login, but getting `signup is disabled` error.

How to onboard new users ?

### Steps to reproduce

1. Create an admin account when app opens for first time.
2. Setup SSO using keycloak
3. Logout from memos
4. Login using SSO (non admin user).

```
{
  "error": "code=401, message=signup is disabled",
  "message": "signup is disabled"
}
```

### Screenshots or additional context

<img width="604" alt="image" src="https://github.com/usememos/memos/assets/12707743/88769d32-0fef-48ae-b4a6-2d0ca8ea1d29">

**Comment by boojack** [comment] 2023-11-17 00:15
You should enable `Allow user signup` first.

<img width="1035" alt="image" src="https://github.com/usememos/memos/assets/24653555/6f7b3ecf-f31e-4675-9640-e295d4008960">

**Comment by debugger24** [comment] 2023-11-17 01:59
It was already enabled.

<img width="1112" alt="image" src="https://github.com/usememos/memos/assets/12707743/8e8c7dff-4246-48a6-b565-6ffa088e090f">

**Comment by debugger24** [comment] 2023-11-17 02:01
Ah just noticed, if I set to false and then set to true again it works.

In initial setup it shows as true but internally it is not true.

**Comment by debugger24** [comment] 2023-11-17 02:06
Also, tried with clean docker run.

Settings API is not sending `allow-signup` but in UI it is shown as true.

<img width="1512" alt="image" src="https://github.com/usememos/memos/assets/12707743/66ea6261-8cbd-4fdb-9735-d7a938de5e0d">

**Comment by boojack** [comment] 2023-11-17 02:09
Thanks for following up, we'll look into the cause of the problem.

**Comment by boojack** [comment] 2023-11-18 04:50
Fixed in https://github.com/usememos/memos/commit/7f7ddf77b84fff2ae080e1a135c983fead9497c2

**Closed by boojack** 2023-11-18 04:50 UTC
Labels: bug
