### ISSUE TITLE
Hope to default to only showing thumbnail images on the list page, and only load the original image after clicking on the picture.

### ISSUE THREAD

**Issue by ttgml** [usememos/memos#3871] opened 2024-09-02 14:26 UTC
### Describe the solution you'd like

After uploading the original image, the page loading becomes very slow. If loading thumbnail images, the speed will be faster and the experience will be better.

### Type of feature

User Experience (UX)

**Comment by RoccoSmit** [comment] 2024-09-02 14:32
Duplicate of https://github.com/usememos/memos/issues/3685

**Closed** 2024-09-02 14:42 UTC
Labels: enhancement
