### ISSUE TITLE
允许重命名标签

### ISSUE THREAD

**Issue by hahahumble** [usememos/memos#1054] opened 2023-02-09 13:55 UTC
### Is your feature request related to a problem?

目前标签名称一旦设定了就无法重命名

### Describe the solution you'd like

增加重命名标签功能，例如：

![image-OYzIi7bJ](https://user-images.githubusercontent.com/81009071/217830850-806f3daf-29dc-4b00-9fb6-ede21f5c3066.png)

![image-GYyUw62s](https://user-images.githubusercontent.com/81009071/217830860-28523674-3722-4d08-98d5-1762e1d11a05.png)

Added the ability to rename tags
1. When the mouse hovers over the tag, the options button appears on the right
2. Click the option button, then the pop-up window appears, which has rename and delete options

**Comment by jxpsert** [comment] 2023-02-09 19:59
Duplicate of #470

**Closed** 2023-02-11 07:23 UTC
Labels: enhancement

**Comment by gitkeniwo** [comment] 2023-02-14 19:52
Obsidian有个[类似的社区插件](https://github.com/pjeby/tag-wrangler)来管理标签.
Obsidian uses a tag tree too and they have [a community plugin](https://github.com/pjeby/tag-wrangler) for this (renaming, merging etc).
