### ISSUE TITLE
v0.22.5 + postgresql v14

### ISSUE THREAD

**Issue by vladimirdulov** [usememos/memos#4102] opened 2024-11-06 10:22 UTC
### Describe the bug

The first time it starts, it crashes with the following error:

```
2024/11/06 09:58:04 ERROR failed to migrate error="strconv.Atoi: parsing \"00_reaction.sql\": invalid syntax\nfailed to convert patch version to int: 00_reaction.sql\ngithub.com/usememos/memos/store.(*Store).getSchemaVersionOfMigrateScript\n\t/home/runner/work/memos/memos/store/migrator.go:233\ngithub.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList\n\t/home/runner/work/memos/memos/store/migrator.go:272\ngithub.com/usememos/memos/store.(*Store).preMigrate\n\t/home/runner/work/memos/memos/store/migrator.go:151\ngithub.com/usememos/memos/store.(*Store).Migrate\n\t/home/runner/work/memos/memos/store/migrator.go:37\nmain.init.func1\n\t/home/runner/work/memos/memos/bin/memos/main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/home/runner/work/memos/memos/bin/memos/main.go:171\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/asm_amd64.s:1695\nfailed to get schema version of migrate script\ngithub.com/usememos/memos/store.(*Store).normalizedMigrationHistoryList\n\t/home/runner/work/memos/memos/store/migrator.go:274\ngithub.com/usememos/memos/store.(*Store).preMigrate\n\t/home/runner/work/memos/memos/store/migrator.go:151\ngithub.com/usememos/memos/store.(*Store).Migrate\n\t/home/runner/work/memos/memos/store/migrator.go:37\nmain.init.func1\n\t/home/runner/work/memos/memos/bin/memos/main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/home/runner/work/memos/memos/bin/memos/main.go:171\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/asm_amd64.s:1695\nfailed to normalize migration history list\ngithub.com/usememos/memos/store.(*Store).preMigrate\n\t/home/runner/work/memos/memos/store/migrator.go:152\ngithub.com/usememos/memos/store.(*Store).Migrate\n\t/home/runner/work/memos/memos/store/migrator.go:37\nmain.init.func1\n\t/home/runner/work/memos/memos/bin/memos/main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/home/runner/work/memos/memos/bin/memos/main.go:171\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/asm_amd64.s:1695\nfailed to pre-migrate\ngithub.com/usememos/memos/store.(*Store).Migrate\n\t/home/runner/work/memos/memos/store/migrator.go:38\nmain.init.func1\n\t/home/runner/work/memos/memos/bin/memos/main.go:61\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/home/runner/work/memos/memos/bin/memos/main.go:171\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/asm_amd64.s:1695"
```

Postgresql v14.9
Memos v0.22.5

Memos v0.22.4 works well in the same config.

### Steps to reproduce

$ mkdir -p /app/code /app/data/data && cd /app/code

$ curl -L https://github.com/usememos/memos/releases/download/v0.22.5/memos_v0.22.5_linux_amd64.tar.gz | tar zxvf -

$ /app/code/memos \
        --mode prod \
        --port 8081 \
        --driver postgres \
        --dsn "postgresql://postgres:password@localhost:5432/memos?sslmode=disable" \
        --data /app/data/data

### The version of Memos you're using.

v0.22.5

**Comment by RoccoSmit** [comment] 2024-11-06 10:40
Duplicate of https://github.com/usememos/memos/issues/3885
See the following pr for more info on how to resolve this https://github.com/usememos/memos/pull/3873
(In short: if you'd like to use PostgreSQL, try the latest version v0.23.0-rc.0)

**Closed** 2024-11-11 05:49 UTC
Labels: bug
