### ISSUE TITLE
Cant Change Creation date:

### ISSUE THREAD

**Issue by samedarkclouds** [usememos/memos#4034] opened 2024-10-17 17:13 UTC
### Describe the bug

Attempting to change the date results in "Invalid Date" appearing where the date is and saving new date results in "Transport error: Not an integer" appearing in a notification pop-up. No choice but to cancel with no date change.

### Steps to reproduce

1: make a note
2: save it
3: go to edit the note
4: click on the date
5: select a different date -> Results in the words "Invalid Date" appearing where the date was and the calendar does not close. Even if you select the same date, this does not change.
6: Click Save -> Results in a notification box that says "Transport error: Not an integer" 
7: no choice but to select cancel to get out of edit. -> Reults in the date remaining unchanged.

### The version of Memos you're using.

Was true in 22.3, upgraded to 22.5 and it still happens (note: In settings it says 23.0)

### Screenshots or additional context

<img width="1363" alt="Screenshot 2024-10-17 at 1 11 23 PM" src="https://github.com/user-attachments/assets/a969101d-39bb-4a66-abc4-86d5b45e443f">
<img width="814" alt="Screenshot 2024-10-17 at 1 11 09 PM" src="https://github.com/user-attachments/assets/ee29d072-62bc-4365-9aea-6e73bbecbeef">

**Comment by RoccoSmit** [comment] 2024-10-17 20:09
Duplicate of https://github.com/usememos/memos/issues/3812

**Closed** 2024-10-18 02:32 UTC
Labels: bug
