### ISSUE TITLE
Wrong hashtag

### ISSUE THREAD

**Issue by bxb100** [usememos/memos#710] opened 2022-12-09 02:57 UTC
### Describe the bug

Write code block with `#`, but it show as a hashtag

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/20685961/206613925-a4fd8f01-1cb7-4600-8611-a62233ee1d69.png">

### Steps to reproduce

see upper image

### Screenshots or additional context

see upper image

**Comment by Zeng1998** [comment] 2022-12-09 04:31
Duplicate of #629

**Closed** 2022-12-09 06:28 UTC
Labels: bug
