### ISSUE TITLE
Tags used in private memos only are visible to other users

### ISSUE THREAD

**Issue by bustikiller** [usememos/memos#3899] opened 2024-09-08 17:22 UTC
### Describe the bug

Tags used exclusively in memos that are private become visible to other users in the MoeMemos mobile applications (both Android and IPhone). This does not happen in the web application, which only displays the tags of the memos I have written. 

In the mobile app, when I click on one of the tags which is not associated with any of my memos, I see an empty list (this is expected). However, since all memos where the tag is used are private, I should not even see these tag exists.

This may be considered an issue in the MoeMemos app. However, the fact that the API exposes the existence of these tags to users that are not meant to see them is, IMHO, a privacy issue. In a way, part of the private memos of other users are made available to unintended recipients.

### Steps to reproduce

1. Start a new instance
2. Create an account Alice
3. Using account Alice, post a private memo using the tag `#helloworld`
4. Log out
5. Create an account Bob
6. Log in to Bob's account using the MoeMemos' app (Android or IPhone) 
7. Click on the _burger_ icon to see the list of tags
8. `#helloworld` should not be visible, but it's included in the list

### The version of Memos you're using.

v0.22.5

### Screenshots or additional context

Reproduced with MoeMemo 0.8.2 (Android) and MoeMemo 1.6 (iPhone)

**Comment by RoccoSmit** [comment] 2024-09-09 03:33
This is probably something that will need to be discussed in MoeMemos first and if its found the issue is in Memos then it should be revisited here.

E.g. Momemos keeps an internal state of all tags returned from API to speed up performance. Nothing Memos can do about that and its a Momemos update to make

**Comment by bustikiller** [comment] 2024-09-09 07:34
@RoccoSmit thanks for the quick reply. I'm going to open an issue on MoeMemos as well.

Regardless of how MoeMemos handles the tags returned by the API, I wonder if these tags should even be returned by the API to users that don't need to know about them. A malicious actor could (without MoeMemos in the equation) take advantage of this fact and obtain the list of tags, which would somehow give partial information about private memos stored in the application.

Thanks again for your time!

**Comment by RoccoSmit** [comment] 2024-09-09 07:50
I had a chance to look at the memos code and the API does allow for all tags to be returned as the user id filter gets set by the consumer and passed to the server rather than the server using the logged in user id

As a rough guess I would assume this has something to do with public memos and getting tags for non signed in users, but not sure why this design decision was made. Someone with more context would need to advise.

**Comment by RoccoSmit** [comment] 2024-09-09 10:31
Note: moving user id filtering from server to client was released in v0.22 (commit: https://github.com/usememos/memos/commit/9265b8e2bd29dd8ab3731d538903ee0495a1aa35)

**Comment by boojack** [comment] 2024-09-09 14:47
@RoccoSmit There is user's personal homepage(/u/username) in Memos, and users who are not logged in can see the public content. As well as for tags, except that they are not shown on the UI yet. The related code is https://github.com/usememos/memos/blob/main/server/router/api/v1/memo_service.go#L925

**Comment by bustikiller** [comment] 2024-09-10 06:50
@boojack thanks for your time. Maybe I didn't explain myself properly. This bug report is about tags only used in private memos that are being exposed to all users. I kindly ask you to reconsider reopening this issue, as this is not what anyone would expect from a _privacy-first_ service. If I'm writing a private memo about the organization of a `#birthday-party`, I would definitely not want my wife (using the same instance) to know about it.

Thanks for considering

**Comment by boojack** [comment] 2024-09-22 01:24
cannot reproduce and the API does not return private data.

**Closed by boojack** 2024-09-22 01:24 UTC
Labels: bug
