### ISSUE TITLE
In the Iphone can't show Calendar, please recover  Timeline page.

### ISSUE THREAD

**Issue by fattyhk** [usememos/memos#3829] opened 2024-08-24 03:13 UTC
### Describe the bug

In the Iphone can't show Calendar, from Timeline page can quick positioning the memos. please recover  Timeline page.

### Steps to reproduce

1.iphone edge open memos
2.can't find the Calendar

### The version of Memos you're using.

0.22.4  

### Screenshots or additional context

![Uploading 无法显示日历.jpg…]()

**Comment by RoccoSmit** [comment] 2024-08-24 03:18
Duplicate of https://github.com/usememos/memos/issues/3828

**Comment by RoccoSmit** [comment] 2024-08-24 03:21
@fattyhk , can you please reattach the screenshot

**Closed** 2024-08-24 12:31 UTC
Labels: bug
