### ISSUE TITLE
Add external MySQL storage support

### ISSUE THREAD

**Issue by selfancy** [usememos/memos#2269] opened 2023-09-22 09:21 UTC
### Is your feature request related to a problem?

Add external MySQL storage support. and custom memos data management

### Describe the solution you'd like

Add external MySQL storage support. and custom memos data management

**Comment by Zeng1998** [comment] 2023-09-23 02:16
Duplicate of #1816

**Comment by athurg** [comment] 2023-09-26 07:23
I'm going to close this PR because it was duplicated of #1816, and working on #2279

**Closed** 2023-09-26 07:22 UTC
Labels: enhancement
