### ISSUE TITLE
Resources are publicly accessible

### ISSUE THREAD

**Issue by Erwyn** [usememos/memos#1006] opened 2023-02-01 15:00 UTC
### Describe the bug

If I add a resource to a memo, I can access it directly with its url although my memo is private.

### Steps to reproduce

1. create a memo only visible to you
2. add a resource
3. in another unauthenticated session browse to the url of the resource

**Comment by Zeng1998** [comment] 2023-02-04 08:09
Duplicate of #822

**Closed** 2023-02-14 03:40 UTC
Labels: bug

**Comment by alexleyn** [comment] 2023-06-21 12:44
Resources are still accessible public. It's impossible to make resource private.
