### ISSUE TITLE
The text embedded in ``` shouldn't be parsed and became a tag

### ISSUE THREAD

**Issue by grigio** [usememos/memos#629] opened 2022-11-28 22:58 UTC
### Describe the bug

The text under ``` shouldn't be parsed

![image](https://user-images.githubusercontent.com/8074/204398143-2ce4db73-8a78-4e73-b5f0-2ffd62b6b21c.png)

it doesn't happen with bold text **

### Steps to reproduce

see the image above

**Comment by ItsNoted** [comment] 2022-11-29 13:31
I confirmed this is happening on my install too.

**Comment by jxpsert** [comment] 2022-11-29 13:33
Duplicate of #595, closed by codeowner.

**Comment by boojack** [comment] 2022-11-29 13:49
The memos front-end has a regex-like parser written in TypeScript. Therefore, the code block can work as expected.

But now there is no markdown parser in the backend, so the tag list api will show the all of the tags including unwanted.

**Closed** 2022-12-22 03:33 UTC
Labels: bug
