### ISSUE TITLE
Markdown table not rendered

### ISSUE THREAD

**Issue by Jesn** [usememos/memos#1899] opened 2023-07-05 08:50 UTC
### Describe the bug

Markdown table not rendered

### Steps to reproduce

add this content to memos

```
| 列标题1 | 列标题2 | 列标题3 |
|---------|---------|---------|
| 单元格1 | 单元格2 | 单元格3 |
| 单元格4 | 单元格5 | 单元格6 |
```

**Comment by mygit20230606** [comment] 2023-07-13 00:39
这个功能非常重要  不知道 为啥 一直不实现

**Comment by RaphaelPour** [comment] 2023-07-27 05:16
I guess this is a duplicate of https://github.com/usememos/memos/issues/1843

**Comment by boojack** [comment] 2023-10-07 15:21
Duplicated with https://github.com/usememos/memos/issues/1843

**Closed by boojack** 2023-10-07 15:21 UTC
Labels: bug

**Comment by mygit20230606** [comment] 2023-10-08 00:14
> Duplicated with #1843 与#1843 重复

是否有计划实现？
